# Generated by Django 4.1.6 on 2023-02-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=200)),
                ('Prn', models.IntegerField(max_length=20)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
    ]
