# Generated by Django 4.1.6 on 2023-02-09 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_date_student_date_rename_prn_student_prn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sub',
            field=models.CharField(default=datetime.datetime(2023, 2, 9, 18, 26, 38, 93804, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
    ]
