# Generated by Django 3.2.17 on 2023-02-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_prn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prn',
            field=models.IntegerField(max_length=20),
        ),
    ]
