# Generated by Django 4.1.6 on 2023-02-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_batchmate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batchmate',
        ),
    ]
