# Generated by Django 4.1.6 on 2023-02-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_student_id_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prn',
            field=models.CharField(max_length=20),
        ),
    ]
